# Generated by Django 5.0.1 on 2026-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_donations', models.IntegerField(default=0)),
                ('new_donations', models.IntegerField(default=0)),
                ('completed_donations', models.IntegerField(default=0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('cancelled_deliveries', models.IntegerField(default=0)),
                ('total_volunteers', models.IntegerField(default=0)),
                ('active_volunteers', models.IntegerField(default=0)),
                ('meals_saved', models.IntegerField(default=0)),
                ('revenue_subscriptions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revenue_deliveries', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('donation_created', 'Donation Created'), ('request_sent', 'Request Sent'), ('delivery_completed', 'Delivery Completed'), ('subscription_upgraded', 'Subscription Upgraded'), ('wallet_recharged', 'Wallet Recharged')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
