# Generated by Django 5.0.1 on 2026-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=500)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('expiry_date', models.DateField()),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='donation_images/')),
                ('category', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('non_veg', 'Non-Vegetarian'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free'), ('other', 'Other')], default='other', max_length=20)),
                ('pickup_time_start', models.TimeField(blank=True, null=True)),
                ('pickup_time_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
