# Generated by Django 5.0.1 on 2026-02-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='donations_d_pickup__b528d1_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['category'], name='donations_d_categor_0fb042_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['expiry_date'], name='donations_d_expiry__4a05c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('donation', 'receiver')},
        ),
    ]
