# Generated by Django 5.0.1 on 2026-02-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
