# Generated by Django 5.0.1 on 2026-02-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0002_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='deliveryrating',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryrating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='deliveries_status_c2a7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['volunteer', 'status'], name='deliveries_volunte_bfacad_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['receiver'], name='deliveries_receive_4dc844_idx'),
        ),
    ]
